alpine-collective/alpinejs-devtools

README.md
Closes #4 
The extension got approved and is now available publicly at https://addons.mozilla.org/firefox/addon/alpinejs-devtools/
=> feature(add-firefox-extension-url)

packages/shell-chrome/assets/panel.html, packages/shell-chrome/src/backend.js, packages/shell-chrome/src/state.js, packages/shell-chrome/src/utils.js
Closes #6 
- make component data `[key]: { value, type }` instead of `[key]: value`
- set `readOnly` for "function" properties
- update styling and what displays based on `readOnly`
FYI since I'll need the shape (`type`) changes for the boolean input, I'll branch from this 😄
=> feat(function-properties-read-only)

packages/shell-chrome/assets/panel.html, packages/shell-chrome/src/backend.js, packages/shell-chrome/src/state.js, packages/shell-chrome/src/utils.js
Should not be merged before #21 
Closes #13 
- populate an `inputType` for each component based on data type (string -> text, boolean -> checkbox, number -> number)
- fix number/boolean data injection for top-level properties
- `eval(data ...` was always quoting the content so don't use it for top-level fields (ie. attributeSequence has no `*`)
Fix for non-top-level boolean/number in #23
=> feat(bool-checkbox)

packages/shell-chrome/src/backend.js, packages/shell-chrome/src/panel.js, packages/shell-chrome/src/state.js, packages/shell-chrome/src/utils.js
Closes #26 
Refactor of backend.js to remove `eval` since it's not strictly necessary & causes a Rollup warning.
- **fix**: setting non-top-level properties to boolean/number
- **fix**: coerce number inputs to number values before updating them in Alpine
Changes:
- create a `set` function inspired by `lodash.set` (see https://lodash.com/docs#set) so we can do `set(data, 'array.0.property.nestedProperty', 'newValue')` instead of using `eval`.
- use `set` in backend.js instead of `eval`.
- format all edited files to 4-space indent
- refactor `flattenSingleAttribute` for Array/Object to be more compact
- change path separator from `*` eg. `array*0*property` to `.`, eg. `array.0.property`
=> fix(number-input) chore(remove-eval) 

packages/shell-chrome/assets/manifest.json
manifest `name` and `description` is what is pulled in on the Firefox `about:addons` page.
=> chore(update-manifest-name-description)

.github/workflows/build.yml, .gitignore, packages/shell-chrome/assets/panel.html, tests/component-list.spec.js, tests/editing.spec.js, tests/init.spec.js, tests/utils.js
Part 2/3 of #37 
- Test that editing strings, numbers, booleans works as expected.
- Test that functions are read-only
- Test that cancelling works as expected
- Add a new util to mock `window.__alpineDevtool.port.postMessage`
- Enable coverage on CI test runs
- Refactor testing
- move jest-dom import to test/utils
- re-export State from test/utils (cleaner test files)
- move away from dom-testing-library query fns in favour of querySelector
=> chore(panel-editing-tests)

packages/shell-chrome/src/backend.js, packages/shell-chrome/src/panel.js
Closes #17
- un-proxies proxy objects by JSON.stringify/JSON.parsing them
- formats edited files
- refactors backend.js `data` generation per component to use `.reduce()` instead of `for of`
**Note**: proxies are undetectable so we take the serialisation/deserialisation hit for all devtools runs.
=> fix(un-proxy-with-json-serialisation)

packages/shell-chrome/assets/manifest.json
From a Firefox addon reviewer:
> This version did not pass the review because of the following issues:
> 1) Extensions defining a content security policy that allows eval ('unsafe-eval') are generally not allowed for security and performance reasons. eval is only necessary in rare cases. 
>
> 2) Using a custom CSP to allow remote script execution is not allowed. We don't allow add-ons to use remote scripts because they can create serious security vulnerabilities.
Remove JSDeliver from allows origins (we're bundling Alpine anyways).
=> fix(csp-only-self-unsafe-inline)

.github/workflows/build.yml, package.json, packages/shell-chrome/assets/manifest.json, rollup.config.js
cc @ryangjchandler but I think this Closes #15 apart from automatic publishing, we've now got it to the point where each commit is tested, built and a versioned artifact ready to upload to Firefox addons gallery is generated.
**Question**: should we delete the `dist/chrome` directory once it's zipped up instead of saving it?
- inject package.json "version" field into manifest at build-time, this means we can use `npm version [patch|minor|major]` and CI takes care of the rest
- add a `package` script (works on *NIX envs) to build & zip extension
- run `npm run package` instead of `npm run prod` in CI to store a ready to submit zip file with the extension as well as bundled code.
=> feat(inject-pkg-version-in-manifest) chore(zip-extension-in-ci)

packages/shell-chrome/assets/panel.html, tests/edit-interactions.spec.js, tests/editing.spec.js
Closes #24
- Cancel on blur/ESC press
- Save on ENTER press
=> feat(input-interaction-shortcuts)

tests/array-editing.spec.js, tests/object-editing.spec.js
closes #37
- Add tests for array/object editing, I'm not going to do any "nested array/object" tests because they'll get complicated and brittle.
=> chore(top-level-array/object-edit-tests)

packages/shell-chrome/src/backend.js
Hey guys, thanks for developing this tool! Hope you don't mind me chiming in. This pull request adds the detection of a Livewire component name in the `getComponentName` method. I've left it further down in priority below the `id` and `name` attribute detection as I guess you may want to be able to override a Livewire component name with something custom.
Alternatively `getComponentName` could potentially return an object depending on what's been detected?
```
{
name: 'foo',
type: 'livewire'
id: 'bar'
}
```
Giving the option for a component in the tree to display as "name#id" with its colour corresponding to type and the id portion more muted in style. Can have a crack at an implementation if you're interested.
Closes #53
=> Added detection for livewire component name

package-lock.json, package.json, packages/shell-chrome/assets/panel.html, rollup.config.js, tailwind.config.js
Closes #65 
- Extract TailwindCSS styles to a CSS file (load said CSS file in panel.html)
- Upgrade rollup-postcss-plugin
- Purge TailwindCSS styles (from ~3MB in a JS bundle to 21K in a CSS file 😄 )
- remove terser since it's changing very little
Configuration/branch | `dist/chrome` (total unpacked) size | panel.js size (minified)
---|---|---|
current master | 3.6M | 3.46M
with terser, tailwind extracted | 148K | 27K
without terser, tailwind extracted | 200K | 27.01K
=> Fix: tailwind build, remove terser

packages/shell-chrome/src/backend.js, packages/shell-chrome/src/detector.js, packages/shell-chrome/src/utils.js, rollup.config.js
Improve situations where the script would kick in before Alpine.js has finished loading:
- on page reload, should be fine as long as Alpine.js loads within 1s of the script initialising (and removes a cannot read property `version` of undefined due to `window.Alpine.version` triggering early)
- for Alpine.js detection (toolbar icon), run a few attempts (will detect Alpine as long as it loads within 400ms of the script)
- refactor rollup config so that each file gets its own bundle (no shared chunks) -> means we can extract some utils out of the backend.js file.
=> Fix: gracefully handle slow-loading Alpine

.github/workflows/build.yml
- run GitHub Actions on PR and master push
- skip Cypress `npm i` (we already have the node_modules, just need the Cypress binary)
=> Improve GH Actions

packages/shell-chrome/src/backend.js, packages/shell-chrome/src/utils.js
For perf reasons, it's not ideal to be passing the whole tree of DOM children of an element to the devtools.
Instead pass the first-level children with their attributes and ignore any further children.
We could maybe re-introduce the full DOM walk once we do partial loading of data as part of #10 
Couple of questions for @KevinBatdorf:
- first of all -> thoughts on this PR?
- further improvements
- should we return the children name instead of name + attributes?
- should we be truncating attribute values? eg. if an element had `x-data` + `x-init` that's a bunch of text that's not necessarily super useful
Note: once this gets merged it'll probably be a good time to roll out `0.0.8` 👍
=> perf: only include top-level children of HTMLElement

package.json, packages/shell-chrome/src/devtools/devtools.js
- when hiding the devtools tab, width of the panel window goes to 0 cache window size and when window width is 0, use cached value
Fixes the following issue:
=> Fix resize pane init

cypress/integration/component.js, packages/shell-chrome/assets/panel.html, packages/shell-chrome/src/utils.js, packages/simulator/example.html, rollup.config.js
One of the todo's of #86 
- fix input type for strings
- replace some `==` with `===`
- add tests for boolean, number and string editing
RFC: strip `:data-testid` bindings on production builds. Eventually might help with perf (fewer bindings to evaluate)... not sure it's necessary yet, thoughts?
=> add tests for boolean, number and string editing

cypress/integration/component.js, package-lock.json, package.json, packages/shell-chrome/src/backend.js, packages/shell-chrome/views/_partials/component.edge
Closes #122 
- fixes a thing I typoed in #120 
- changes some `==` to `===`
- make id increment post assignment as id
- remove `observer` global and assign to `window.__alpineDevtool`
Create `$x0` - `$xN` (0-N is the component id)
=> Feature: inject component globals

package-lock.json, package.json, packages/shell-chrome/src/utils.js, tailwind.config.js, tests/utils.spec.js
- upgrade Alpine.js version
- fix version-detection bug with 2.8.0 (was returning false when it hits `0`)
- fix orange/cool-gray that was broken by TailwindCSS v2 upgrade
- bump version to 0.1.0 (the orange/cool-gray stuff should go out, it's a regression)
=> Chore: upgrade Alpine.js version, fix version detection issues + prep 0.1.0

packages/shell-chrome/src/backend.js
- refactor to a class + add init() function to get rid of `window.__alpineDevtools` shenanigans
=> refactor(__alpineDevtool in backend.js to a class)

package-lock.json, package.json, packages/shell-chrome/assets/manifest.json
Follow up to #147 #149 
After raising a support ticket with Chrome Web Store, this was in their response
> Tabs permission is required when accessing title, url, pendingUrl and favIconUrl properties of tabs.
And this from the docs 🙈 should've "read the manual" (https://developer.chrome.com/docs/extensions/reference/tabs/#manifest)
> You can use most chrome.tabs methods and events without declaring any permissions in the extension's manifest file. However, if you require access to the url, pendingUrl, title, or favIconUrl properties
=> remove tabs permission

packages/shell-chrome/src/backend.js
fix `Uncaught SyntaxError: redeclaration of let AlpineDevtoolsBackend`
Reproduction steps:
- open a page with Alpine
- open devtools
- go to Alpine devtools tab
- close the devtools
- re-open devtools
- go to Alpine devtools tab
Expected: loads fine
Actual: doesn't load (hits an error)
In console, you get a SyntaxError due to redeclaration of `AlpineDevtools`
=> fix devtools class scope

.github/FUNDING.yml, cypress/integration/component.js, cypress/integration/warning.js, package-lock.json, package.json, packages/shell-chrome/src/backend.js, packages/shell-chrome/src/devtools/app.js, packages/shell-chrome/src/devtools/devtools.js, packages/shell-chrome/src/devtools/state.js, packages/shell-chrome/views/_components/tab-link.edge, packages/shell-chrome/views/_partials/data/attribute.edge, packages/shell-chrome/views/_partials/footer.edge, packages/shell-chrome/views/_partials/tabs/warnings.edge, packages/shell-chrome/views/panel.edge, packages/simulator/example.html, tailwind.config.js
Part 1 of #126
Changes:
- change footer text (`X component(s), X warning(s)`), make the text a link to the relevant tab
- intercept Alpine's warnings for eval errors
- implement initial UI for "Warnings" (only contains eval warnings)
- add/update tests
Chore:
- move purple colour into Tailwind config
- prevent default on tab links
- upgrade Cypress
Needs feedback:
- do we need to debounce the "scroll to last element"?
- should we scroll to last element when changing tabs?
- thoughts on using `pauseMutationObserver`? @SimoTod 
- design feedback (one for @stephenoldham)
- should I take the `devOnly` checks out? (probably should if we're intending to roll this out, could be a separate PR)
=> Feature: add eval warnings

package-lock.json, package.json, packages/shell-chrome/src/backend.js, packages/shell-chrome/src/devtools/devtools.js, packages/shell-chrome/views/_partials/footer.edge, packages/shell-chrome/views/_partials/header.edge, packages/shell-chrome/views/_partials/tabs/warnings.edge, packages/shell-chrome/views/panel.edge
Closes #126 
- Avoid patching `console.warn` when possible (Alpine.js attaches debug info to error/unhandledrejection's)
- remove `devOnly` flags for warnings tab
- add warning tab message when user is on Alpine <2.8.0
- upgrade Alpine.js to 2.8.1
=> feat(global alpine errors)

.github/workflows/build.yml, README.md, package.json, rollup.config.js
Switch to Node 14 to run CI: Node 12 is now is "Maintenance LTS", Node 14 is "Active LTS" 
Add a note in the README.
Add "start:ci" that runs the server without watching for changes.
=> chore(ci-node-14)

cypress/integration/component.js, packages/shell-chrome/views/_partials/data/attribute.edge
Alpine-rendering optimisations for #179 
Optimises Alpine.js `x-for` rendering:
- use `x-if`'s (instead of x-show) 
- removes unnecessary `$nextTick`
Nice spot @KevinBatdorf 👍 , here's alpinetoolbox, much faster and didn't have to change much (`x-show` -> `x-if`)
=> perf (attribute-x-for-rendering)

cypress/integration/component.js, packages/shell-chrome/src/backend.js, packages/shell-chrome/src/constants.js, packages/shell-chrome/src/devtools/app.js, packages/shell-chrome/src/devtools/devtools.js, packages/shell-chrome/src/devtools/state.js, packages/shell-chrome/src/utils.js, packages/shell-chrome/views/_partials/component.edge, packages/shell-chrome/views/_partials/data/attribute.edge, packages/shell-chrome/views/_partials/tabs/components.edge, packages/simulator/example.html, packages/simulator/navigation-target.html
Closes #174 
Closes #10 the perf limitation doesn't seem to be the user's DOM, looping through the components is much faster if we don't do anything with the component data, opened a separate performance issue to optimise loading of components with lots of data -> #179
Todo:
Panel load is in tens of seconds, (using latest published Devtools version `v0.3.0`)
Panel load feels almost instant (using a prod build from this PR)
=> feat perf(update-messaging)

cypress/integration/component.js, packages/shell-chrome/src/devtools/state.js, packages/shell-chrome/views/_partials/data/attribute.edge, packages/simulator/example.html
Follow-up for #174 
Fixes:
- maintain attribute "open" state across component data updates
- receive updates for selected component if you hover without clicking another one
=> fix(maintain-open-attribute) fix(track-selected-id-on-other-hover-no-click)

package-lock.json, package.json, tests/utils.spec.js
uvu + esm + linkedom for HTML/DOM
- test runs are faster (although it's splitting hairs, Jest was reporting 2s, uvu <1s)
- we don't use all the Jest features
- 600 fewer packages to install probably due to Babel/JSDOM more than Jest
- before `added 1448 packages in 14.321s`
- after `added 828 packages in 11.358s`
This change is up for debate Jest + Babel + JSDOM is probably the more widely adopted so happy not to make this switch.
Our key tests are written using Cypress so we could drop this suite altogether.
=> refactor(switch unit tests from jest + babel to uvu + esm)

packages/shell-chrome/src/devtools/panel.js
Fixes issue where panel crashes due to 'devtools' being undefined
=> fix(add-panel-globals-before-injecting-backend)
