README.md, package.json, packages/shell-chrome/assets/alpine.html, packages/shell-chrome/assets/manifest.json, packages/shell-chrome/assets/panel.html, packages/shell-chrome/src/devtools-background.js, packages/shell-chrome/src/proxy.js
Just to make the naming consistent 😄 thanks again for taking the initiative on this @Te7a-Houdini
=> chore(naming: AlpineJs -> Alpine.js)

.gitignore, README.md, packages/shell-chrome/assets/panel.html
Relates to #3 and #4.
Keen to make the PR now since there's already a ton of layout changes.
=> 2-column/responsive layout + FF dev instructions

.editorconfig, .github/workflows/build.yml
Part 1 of --> #15 
Builds using GitHub Actions and stores `./dist/chrome` as an artifact
=> chore(add-ci-build)

package.json, packages/shell-chrome/assets/manifest.json
bump version in package.json and manifest
For #31
=> release 0.0.2

.github/workflows/build.yml, babel.config.js, package-lock.json, package.json, packages/shell-chrome/assets/panel.html, tests/component-list.spec.js, tests/init.spec.js, tests/utils.js
First part of #37 
- add testing dependencies (jest, jest-dom, dom-testing-library, babel-preset-env)
- configure babel with preset-env for testing
- create util to load up `panel.html` body without the panel.js script include
- create util to generate a component object as expected from State
- add initialisation sanity test (ie. Alpine starts up correctly on an empty panel.html)
- add component-list sanity tests (injected components are visible, clicking on a component brings up the data pane with right values)
=> chore(setup-tests)

packages/shell-chrome/assets/panel.html, packages/shell-chrome/src/state.js, tests/arrow-toggle.spec.js
Closes #34
- fix childId match regex (had a `*` instead of `.`)
- this is actually the main change, see https://github.com/Te7a-Houdini/alpinejs-devtools/pull/36/files#diff-ce89d3d52d88bf27196347b55dd78924R77
- refactor loose checks in state.js 
- formats state.js
- adds test for arrow functionality
=> fix(collapse-object-array-property)

packages/shell-chrome/assets/panel.html, packages/shell-chrome/src/backend.js, tests/utils.js
Closes #28
You can test this with the following HTML
```html
<div id="app" x-data="{ hello: 'world' }">
<span x-text="hello"></span>
</div>
<div x-data="myFn()">
<span x-text="hello"></span>
</div>
<div name="component" x-data="{ hello: 'world' }">
<span x-text="hello"></span>
</div>
<div role="combobox" x-data="{ hello: 'world' }">
<span x-text="hello"></span>
</div>
<script>
function myFn() {
return {
hello: 'world'
}
}
</script>
```
=> feat(name-components)

packages/shell-chrome/src/backend.js, packages/shell-chrome/src/panel.js, packages/shell-chrome/src/state.js
=> fix: reloading the page reloads the devtools

packages/shell-chrome/src/proxy.js
=> fix connector duplication issue by wrapping in a closure

package-lock.json, package.json, packages/shell-chrome/assets/panel.html, packages/shell-chrome/src/panel.js, packages/shell-chrome/src/state.js, packages/shell-chrome/src/utils.js, rollup.config.js, tests/example.html
=> Feature: inject/fetch alpine.js latest version

.github/workflows/build.yml, packages/shell-chrome/src/utils.js
Closes #77 
Branched off of #79 since that PR is moving a function to another file.
=> Support LiveView view name for component name

packages/shell-chrome/assets/panel.html, packages/shell-chrome/src/devtools/app.js, packages/shell-chrome/src/devtools/style.css, packages/shell-chrome/src/devtools/styles.css
- rename `style.css` -> `styles.css`
- move relevant panel.html inline styles to `styles.css`
=> Fix missing styles in simulator

packages/shell-chrome/src/backend.js, packages/shell-chrome/src/utils.js, packages/simulator/example.html
Closes #101 
Makes #96 an enhancement rather than a bug.
=> handle unserializable/stringify-able fields

package-lock.json, package.json, packages/shell-chrome/assets/panel.html, packages/shell-chrome/src/devtools/app.js, tailwind.config.js
This PR adds Split Grid to allow for resizing of the components/data panel split. An initial stab at this...see what you think to the code organisation/approach.
Also as an aside, there seems to be some funky tabbing/alignment going on in the panel.html code. May be worth us settling on a standard.
=> Add resizable panes to layout

package-lock.json, package.json, packages/shell-chrome/assets/panel.html, tailwind.config.js
Looks good. Added a small improvement to the boolean checkbox UX/styling. Resolves #114
=> Tailwindcss Upgrade to v2

.github/workflows/build.yml, README.md
- add chrome/FF badges
- add action to cancel redundant GH action runs (eg. when you push before the previous run has completed)
=> Add Chrome/FF store badges

packages/shell-chrome/src/backend.js
Example reproduction steps: open panel, close devtools and re-open them.
Using `let` in the top-level scope of `backend.js` causes runtime issues if backend.js gets injected multiple times.
Not sure how to test for this, maybe concatenate backend.js with itself and check there are no syntax errors?
=> Fix crash on backend.js re-injection

packages/shell-chrome/src/backend.js, packages/shell-chrome/src/devtools/state.js, packages/shell-chrome/views/_partials/component.edge
Closes #127.
Problem seems to be `0` being considered falsy, so just checking if it's truthy or equal to `0` is the simplest solution. Open to more solutions too.
=> fix: component id 0 not being de-selected

cypress/integration/component.js, cypress/integration/load.js, packages/shell-chrome/src/devtools/devtools.js, packages/shell-chrome/views/panel.edge, packages/simulator/dev.js, packages/simulator/no-components.html
=> fix(show 'no components' when none found)

cypress/integration/component.js, packages/shell-chrome/views/_partials/data/attribute.edge
use dynamic data-testid's that contain the attribute/field name to be able to fetch in the data panel more easily.
=> fix(improve tests)

packages/shell-chrome/assets/manifest.json
=> Remove contextMenus and storage permissions

.github/FUNDING.yml, cypress/integration/component.js, cypress/integration/warning.js, packages/shell-chrome/src/devtools/devtools.js, packages/shell-chrome/views/_partials/footer.edge, packages/shell-chrome/views/_partials/tabs/warnings.edge
Tests have been updated to allow for differences in the UI. Also may have snook in a little change to the funding yaml...💰👀😉
=> Small style changes to warnings tab and footer status messages

packages/shell-chrome/src/devtools/devtools.js
#158 improve logging in simulator
=> chore(no-log-error-on-dev)

packages/shell-chrome/views/_partials/data/attribute.edge
Closes #103 
No tooltip, use title + link 🤷
=> feat(link to GH discussions on unserializable value)

cypress/integration/component.js, packages/simulator/example.html
Relates to #177 
Closes #86 (pre-emptively closes but completes the todo list)
=> Add nested array/object toggling/editing test

cypress/integration/component.js, packages/shell-chrome/src/backend.js, packages/shell-chrome/src/devtools/app.js, packages/shell-chrome/src/devtools/state.js, packages/shell-chrome/views/_partials/component.edge, packages/simulator/example.html, packages/simulator/navigation-target.html
This is already an issue on master, never noticed it though.
Not sure whether we need to do better than `btoa` (base64 encoding).
=> fix(reset selection on nav)

packages/shell-chrome/src/backend.js, packages/simulator/navigation-target.html
=> Fix alpine v3 crash

packages/shell-chrome/src/backend.js, packages/simulator/v3.html
Should stop the devtools crashing
Closes #289 
Closes #295
=> fix(handle-undefined-datastack)
